; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s --mtriple=wasm32-unknown-unknown -mcpu=mvp -mattr=+reference-types | FileCheck --check-prefixes CHECK,CHK32 %s
; RUN: llc < %s --mtriple=wasm64-unknown-unknown -mcpu=mvp -mattr=+reference-types | FileCheck --check-prefixes CHECK,CHK64 %s

; Function Attrs: nounwind
define hidden ptr @TrampolineCall(ptr noundef writeonly captures(none) initializes((0, 4)) %okay, ptr noundef readonly %f, ptr noundef %a, ptr noundef %b, ptr noundef %c) local_unnamed_addr #0 {
entry:
  store i32 1, ptr %okay, align 4, !tbaa !2
  %0 = tail call i32 (ptr, ...) @llvm.wasm.ref.test.func(ptr %f, ptr null, token poison, ptr null, ptr null, ptr null)
  %1 = icmp eq i32 %0, 0
  br i1 %1, label %if.end, label %if.then

if.then:                                          ; preds = %entry
  %2 = tail call ptr %f(ptr %a, ptr %b, ptr %c) #2
  br label %return

if.end:                                           ; preds = %entry
  store i32 0, ptr %okay, align 4
  br label %return

return:                                           ; preds = %if.end, %if.then
  %3 = phi ptr [ %2, %if.then ], [ null, %if.end ]
  ret ptr %3
}

!2 = !{!3, !3, i64 0}
!3 = !{!"int", !4, i64 0}
!4 = !{!"omnipotent char", !5, i64 0}
!5 = !{!"Simple C/C++ TBAA"}

declare void @use(i32 noundef) local_unnamed_addr #1
